# Site settings
title: Peter Christopher Allen
description: 'Business Card Page'
url: 'https://petercallen.github.io/'
baseurl: ''
profilepic: '/images/allen_profile.jpg'
bkimage: '/images/bk1.jpg'
font_awesome: 'fb5c482c74.js'

author:
  name: 'Peter Christopher Allen'
  email: pcallen0225@gmail.com
  orcid: 0000-0002-3950-9539 
  twitter_username: PeterAllen225
  github_username:  PeterCAllen


# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md']
